%% DISSIMMILARITY DATASET MPEG7CS
clear all
close all;
clc
%% ADD PATH OF MPEG7CS DATABASE FROM YOUR COMPUTER
path='D:\Matlab\MATLAB\Doctorado\SIMILARITY\Demo\Demo\MPEG7CS\MPEG7CS_C';
%% SELEC NUMBER OF SEMGMENT m
%% SELEC VALUE OF EPSILON [0,1]
m=19;
epsilon=0.67;
dissimilarityMPEG7CS(path,m, epsilon)
%%